### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by chasinglogic** [comment]
Done upstream

**Comment by aminya** [comment]
@chasinglogic It was done incorrectly. See #16

**Comment by chasinglogic** [comment]
In what way the lock file and the toml file have the new version and that issue is unreproducable?

**Comment by aminya** [comment]
It is because you copied the drive feature from this PR, but used the wrong version number. The drive feature is only available on 1.0

**Comment by chasinglogic** [comment]
You can see here: https://github.com/chasinglogic/licensure/commit/9162bbfe04dab6a8081ec3dedf43cc52e3bd88cd#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R20

That Serde 1.0 was used in 0.2.0

**Comment by aminya** [comment]
The commit was forced-pushed at some point. The originally tagged commit is now out of the tree:
https://github.com/chasinglogic/licensure/blob/0.2.0/Cargo.toml#L20

**Comment by aminya** [comment]
Please tag a new 0.2.1 and release it to fix 0.2.0.

**Comment by chasinglogic** [comment]
I already did: https://crates.io/crates/licensure

**Comment by aminya** [comment]
Thank you! I have also updated another dependency that required code changes. I'll make a PR.

**Pull request closed without merging**
