### PR TITLE
fix: update reqwest - add async/await to the async functions

### PR DESCRIPTION
**Pull request by aminya**
Please use "high whitespace changes" to see the diff in the indented main function.

### CODE REVIEW

**Comment by chasinglogic** [comment]
Since we're not doing anything concurrently I think introducing async isn't worth it. I try to avoid [What Color is Your Function?](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) when possible.

**Comment by aminya** [comment]
@chasinglogic The new versions of reqwest are async by default. That's why we SHOULD use async/await unless you want to use outdated/unsupported packages in the dependency chain.

**Comment by chasinglogic** [comment]
I have upgraded reqwest to 0.11 now using the blocking feature which required very minimal code changes 👍

**Comment by aminya** [comment]
Great. That works too.

**Pull request closed without merging**
