### PR TITLE
fix: add an option for text unwrapping

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by chasinglogic** [comment]
I know this is quite old but we need to make this default to true to not break existing usages. If I don't get a response by tomorrow I will merge this and add the fix myself.

Thanks for your contribution and sorry for being absent so long!

**Comment by aminya** [comment]
No worries. Thank you. 

The default is already set to true in the config file.

**Comment by chasinglogic** [comment]
I meant that it needs to default to true _if not specified_ as it won't be in existing config files

**Comment by aminya** [comment]
Where else do you set the default? Nothing like that is implemented right now as far as I see. 

Feel free to merge this and add that on top.

**Comment by chasinglogic** [comment]
I had to do a decent chunk of fixupx on top of this so I've merged this via the command line.

**Pull request closed without merging**
