### PR TITLE
 feat: Add the capability for year ranges in license headers 

### PR DESCRIPTION
**Pull request by chasinglogic**
Licensing configs can now specify an end_year and start_year and
generated headers will use those year ranges.

Additionally you may instead specify use_dynamic_year_ranges and we will
parse the start_year and end_year from commit information for each file
as we start to license it.

### CODE REVIEW

**Comment by hcldan** [comment]
I tested 5a3ded3bc58a7a6a36c3d3ec0b6666c466c5b9c1 and it seems to be working well for my projects.

Thanks again!

**Comment by hcldan** [comment]
Any chance on a release with this in it?

**Comment by chasinglogic** [comment]
@hcldan This was released the day it was merged

You can see it was in the 0.5.0 release:
https://github.com/chasinglogic/licensure/releases/tag/0.5.0

**Comment by hcldan** [comment]
image

**Comment by hcldan** [comment]
I guess the tag got moved or applied to a later commit than the release commit.

**Comment by chasinglogic** [comment]
I'm not sure what's going on or what I'm supposed to see in that screenshot but I can confirm that people are using this feature with the released versions of licensure

**Pull request merged**
